### ISSUE TITLE
Updating esbuild version

### ISSUE THREAD

**Issue by juancampa** [wilsonzlin/esbuild-rs#4]
Our current version of esbuild es getting a bit old. As of today it sits aroud ~800 commits behind upstream. Any plans to update it?

@wilsonzlin if you post a general guideline on how you generated esbuild-lib I can help you keep it up-to-date.

**Comment by wilsonzlin** [comment]
I've just updated it to the latest version `0.12.18`.  Updating is a bit tedious and I'd love for anyone to help out. There are two parts:

- Updating [esbuild-lib](https://github.com/wilsonzlin/esbuild-lib): there's an [UPSTREAM.md](https://github.com/wilsonzlin/esbuild-lib/blob/master/UPSTREAM.md) file in the repo that contains instructions.
- Updating esbuild-rs (this library): I'll write up something soon, but it should be possible to figure out by looking through the code, which is not that large and mostly repetitive.

**Comment by juancampa** [comment]
Sweet! Thanks a lot! Next time I'd gladly take a stab at it.
